### ISSUE TITLE
[IOS] Pod is not installed when building with dynamiclinks

### ISSUE THREAD

**Issue by guibarbosadev** [chemerisuk/cordova-plugin-firebase-inappmessaging#6]
Steps to reproduce:
- `cordova create test-firebase-inappmessaging`
- `cordova plugin add cordova-plugin-firebase-inappmessaging`
- `cordova plugin add cordova-plugin-firebase-dynamiclinks --variable APP_DOMAIN="foo.com.br" --variable PAGE_LINK_DOMAIN="foo.page.link"`
- `cordova platform add ios`

Expected result
- Build successfully
- All pods to have been installed

Result:
- Pod Firebase/InAppMessagingDisplay isn't installed

Output when adding ios platform: 
> cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@5.0.1
Installing "cordova-plugin-firebase-dynamiclinks" for ios
Running command: pod install --verbose
Installing "cordova-plugin-firebase-inappmessaging" for ios
Installing "cordova-plugin-firebase-analytics" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/18digital-8/workspaces/cordova/test-dynamiclinks-and-inappmessaging/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Failed to install 'cordova-plugin-firebase-inappmessaging': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/18digital-8/workspaces/cordova/test-dynamiclinks-and-inappmessaging/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
pod: Command failed with exit code 31

Output when checking dependencies:
- cd platform/ios
- pod install

> Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (~> 6.1.0)

> None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (~> 6.1.0)`.

> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.

**Comment by guibarbosadev** [comment]
This commit solved the problem https://github.com/chemerisuk/cordova-plugin-firebase-inappmessaging/commit/7a0ee00d8d17e7945fa7148a03743c75dcea87af.

**[SOLUTION]** Simply update your cordova-plugin-firebase-inappmessaging to 3.0.0
